# Projection and decision support

## ...

Use CoCT water crisis as the example?

There’s more to decision making than models and not all decisions are amenable to modelling...

"Quantitative approach to decision-making produces the best results when the problem is clearly defined, several alternatives exist, and decision outcomes are easily measurable. However, in the case that many external factors are outside of the decision-maker's control and their probability is unknown, the quantitative methods can become unreliable." - https://study.com/academy/lesson/the-quantitative-approach-to-decision-making-methods-purpose-benefits.html#:~:text=we've%20learned.-,The%20quantitative%20approach%20is%20to%20make%20an%20optimal%20decision%20by,helps%20managers%20solve%20complex%20problems. 

We can model properties and performance measures, but decisions are ultimately about values and often require evaluating trade offs among properties with incomparable units -e.g. people housed/fed/watered vs species saved from extinction…

In the context of ecology, the first step is making sure that the environment is even considered among the objectives and performance measures…

Decisions within conservation/ecology…

From adaptive management to ecoforecasting? (With AM as the qualitative model that subsequently becomes more quantitative as more data and understanding are accumulated…
